[package]
name = "tumblr_steam_shovel"
version = "0.0.1"
authors = ["Zack M. Davis <code@zackmdavis.net>"]

[dependencies]
oauth-client = "0.3.2"
reqwest = "0.7.1"
serde = "1.0.0"
serde_derive = "1.0.10"
serde_json = "1.0"
toml = "0.4"
